EL:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: EL
    username: root
    password: 12301

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234321!
      database: 0